service:
  name: sls-template

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  test:
    handler: src/handler.lambdaHandler
    events:
      - http:
          method: get
          path: test
